version: "3.3"

services:
  master: 
    image: ozlevka/elastic:5.6.3
    command: ["/bin/sh", "elasticsearch", "--E", "cluster.name=test", "--E", "network.host={{.HOST_IP}}"]
    ports:
      - "9200:9200"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == master