version: "3.3"

services:
  master: 
    image: ozlevka/elastic:5.6.3
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=_eth0_ --E discovery.zen.ping.unicast.hosts=master --E node.master=true --E node.data=false"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.master == yes
    networks:
      - elastic

  elastic:
    image: ozlevka/elastic:5.6.3
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=_eth2_ --E http.host=0.0.0.0 --E discovery.zen.ping.unicast.hosts=master --E node.master=false --E node.data=true"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.data == yes
    ports:
      - 9200:9200
    networks:
      - elastic


networks: 
  elastic:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16