version: "3.3"

services:
  master: 
    image: ozlevka/elastic:5.6.3-deb
    command: ["su", "-","elastic", "-s", "/bin/sh", "-c", "'/opt/elasticsearch/bin/elasticsearch --E cluster.name=test --E network.host=0.0.0.0 --E discovery.zen.ping.unicast.hosts=master'"]
    ports:
      - "9200:9200"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == master
    networks:
      - elastic

networks: 
  elastic:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16