version: "3.3"

services:
  master: 
    image: ozlevka/elastic:5.6.3-deb
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=_eth0_ --E discovery.zen.ping.unicast.hosts=master --E node.master=true"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == master
    networks:
      - elastic

  elastic:
    image: ozlevka/elastic:5.6.3-deb
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=_eth0_ --E discovery.zen.ping.unicast.hosts=master --E node.master=false --E node.data=true"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == data
    networks:
      - elastic

networks: 
  elastic:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16