version: "3.3"

services:
  master: 
    image: ozlevka/elastic:5.6.3-deb
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=_eth0_ --E discovery.zen.ping.unicast.hosts=master --E node.master=true --E node.data=false"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.master == yes
    networks:
      - elastic

  elastic:
    image: ozlevka/elastic:5.6.3-deb
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=_eth0_ --E discovery.zen.ping.unicast.hosts=master --E node.master=false --E node.data=true"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.data == yes
    networks:
      - elastic

  proxy:
    image: ozlevka/meetup-proxy:1.0
    ports:
      - 8080:8080
    environment:
      USER: "elastic"
      PASS: "elastic_admin_17"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == proxy
    networks:
      - elastic



networks: 
  elastic:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16