version: "3.3"

services:
  master: 
    image: ozlevka/elastic:5.6.3-deb
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=_eth1_ --E discovery.zen.ping.unicast.hosts=master"
    ports:
      - "9200:9200"
    deploy:
      mode: global
    networks:
      - elastic

networks: 
  elastic:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16